package main

import (
	"jhpark/echo-guide-test/db/userdb"
	"jhpark/echo-guide-test/router"
	"jhpark/echo-guide-test/router/middleware"
	"jhpark/echo-guide-test/user"
	"net/http"

	_ "jhpark/echo-guide-test/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

//	@title			Swagger Example API
//	@version		1.0
//	@description	jhpark API
//	@title			jhpark API

//	@host		127.0.0.1:1323
//	@BasePath	/api

//	@schemes	http https
//	@produce	application/json
//	@consumes	application/json

func main() {
	r := router.New()

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	rs := middleware.NewRequestStat()
	r.GET("/stats", rs.Stats)

	v1 := r.Group("/api", rs.Process)

	ud := userdb.NewDBHandler()
	defer ud.Close()

	uh := user.NewHandler(ud)

	uh.RegisterRoutes(v1)

	r.GET("/", func(c echo.Context) error {
		return c.HTML(http.StatusOK, `
			<h1>Welcome to Echo!</h1>
			<h3>TLS certificates automatically installed from Let's Encrypt :)</h3>
		`)
	})
	r.Logger.Fatal(r.Start(":1323"))
	//r.Logger.Fatal(r.StartTLS(":1323", "server.crt", "server.key"))

	//r.Logger.Fatal(r.StartAutoTLS(":1323"))
}
